spring:
  port: ${PORT:8080}
  profiles:
    include: jwt
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

oauth2:
  google:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_PW}
    redirect-uri: ${REDIRECT_URI}
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
    auth-uri: https://accounts.google.com/o/oauth2/auth?access_type=offline

imgbb:
  api:
    key: ${IMAGE_API}

image:
  server:
    url: ${IMAGE_SERVER_URL}

llm:
  server:
    url: ${LLM_SERVER_URL}

server:
  forward-headers-strategy: native
